bind = SUPER, X, exec, plasm process --preset fix-pt
bind = SUPER, F, exec, plasm process-all --preset fix-pt
bind = SUPER, ALT, V, exec, plasm paste-all
bind = SUPER, V, exec, plasm pop
bind = CTRL, C, exec, plasm push
bind = SUPER, B, exec, plasm status
